/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furqon0387;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author furqo
 */
public class dtPembayaranPlg0387 extends javax.swing.JFrame {
    private Connection conn = new koneksi0387().connect();
    private DefaultTableModel tabmode;
    Calendar cal = Calendar.getInstance();
    int tahun = cal.get(Calendar.YEAR);
    int bulan = cal.get(Calendar.MONTH) + 1;
    int hari = cal.get(Calendar.DAY_OF_MONTH);
    String tanggal = tahun+"-"+bulan+"-"+hari;
    
    protected void datatabeltgk(){
        Object[] Baris ={"No Rekening","No Pelanggan","Nama Pelanggan","Golongan","Alamat","Pemakaian","Tanggal Tagihan","Tagihan","Status"};
        tabmode = new DefaultTableModel(null, Baris);
        tbTunggakan.setModel(tabmode);
        String sql = "SELECT * FROM `pembayaran` WHERE MONTH(`update_stand`) <= "+bulan+" AND `status_pembayaran` = 1;";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                Object[] obj = new Object[9];
                obj[0] = hasil.getString("no_rek");
                obj[1] = hasil.getString("no_pel");
                obj[2] = hasil.getString("nama_pel");
                obj[3] = hasil.getString("golongan");
                obj[4] = hasil.getString("alamat");
                obj[5] = hasil.getString("pemakaian");
                obj[6] = hasil.getString("update_stand");
                obj[7] = hasil.getString("tagihan");
                obj[8] = hasil.getString("status_pembayaran");
                tabmode.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
      }
    }
    private DefaultTableModel tabelmode;
    
    protected void datatabelbyr(){
        Object[] Baris ={"No Rekening","No Pelanggan","Nama Pelanggan","Golongan","Alamat","Pemakaian","Tanggal Bayar","Tagihan","Status"};
        tabmode = new DefaultTableModel(null, Baris);
        tbPembayaran.setModel(tabmode);
        String sql = "SELECT * FROM `pembayaran` WHERE MONTH(`update_stand`) = "+bulan+" AND `status_pembayaran` = 2;";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                Object[] obj = new Object[9];
                obj[0] = hasil.getString("no_rek");
                obj[1] = hasil.getString("no_pel");
                obj[2] = hasil.getString("nama_pel");
                obj[3] = hasil.getString("golongan");
                obj[4] = hasil.getString("alamat");
                obj[5] = hasil.getString("pemakaian");
                obj[6] = hasil.getString("tanggal_pembayaran");
                obj[7] = hasil.getString("tagihan");
                obj[8] = hasil.getString("status_pembayaran");
                tabmode.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
      }
    }

    /**
     * Creates new form dtPembayaranPlg0387
     */
    public dtPembayaranPlg0387() {
        initComponents();
        datatabeltgk();
        datatabelbyr();
        btnCheckout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrJk = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNoPel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JLabel();
        btnBersih = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTagihan = new javax.swing.JTextField();
        txtPemakaian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNoOver = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaOver = new javax.swing.JLabel();
        txtNoRek = new javax.swing.JTextField();
        cbGol = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPembayaran = new javax.swing.JTable();
        txtCaridtPembayaran = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTunggakan = new javax.swing.JTable();
        txtCariDtTagihan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(60, 30));
        setMinimumSize(new java.awt.Dimension(1250, 675));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans Extrabold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PEMBAYARAN");

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nomor Rekening");

        txtNoPel.setEditable(false);
        txtNoPel.setBackground(new java.awt.Color(0, 102, 255));
        txtNoPel.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoPel.setForeground(new java.awt.Color(255, 255, 255));
        txtNoPel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoPel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPelKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Pelanggan");

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pelanggan");

        btnCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Purchase_Order_48px.png"))); // NOI18N
        btnCheckout.setMinimumSize(new java.awt.Dimension(88, 50));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
        });

        btnBersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Broom_50px.png"))); // NOI18N
        btnBersih.setMinimumSize(new java.awt.Dimension(88, 50));
        btnBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBersihMouseClicked(evt);
            }
        });

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(0, 102, 255));
        txtNama.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tagihan");

        txtTagihan.setEditable(false);
        txtTagihan.setBackground(new java.awt.Color(0, 102, 255));
        txtTagihan.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtTagihan.setForeground(new java.awt.Color(255, 255, 255));
        txtTagihan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        txtPemakaian.setEditable(false);
        txtPemakaian.setBackground(new java.awt.Color(0, 102, 255));
        txtPemakaian.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtPemakaian.setForeground(new java.awt.Color(255, 255, 255));
        txtPemakaian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel12.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pemakaian");

        txtNoOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoOver.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Back_To_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        txtNamaOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNamaOver.setForeground(new java.awt.Color(255, 0, 0));
        txtNamaOver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaOverKeyTyped(evt);
            }
        });

        txtNoRek.setBackground(new java.awt.Color(0, 102, 255));
        txtNoRek.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoRek.setForeground(new java.awt.Color(255, 255, 255));
        txtNoRek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoRek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoRekKeyPressed(evt);
            }
        });

        cbGol.setBackground(new java.awt.Color(0, 102, 255));
        cbGol.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        cbGol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sosial", "Rumah Tangga", "Industri" }));

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Golongan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbGol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(158, 158, 158))
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtPemakaian)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtTagihan, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(380, 380, 380))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNoOver, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(txtNamaOver, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNoPel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBersih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoRek, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoRek, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoOver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoPel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaOver, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 36, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 680);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbPembayaran.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)));
        tbPembayaran.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        tbPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        tbPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPembayaran);

        txtCaridtPembayaran.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtCaridtPembayaran.setForeground(new java.awt.Color(0, 102, 255));
        txtCaridtPembayaran.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtCaridtPembayaran.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        txtCaridtPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCaridtPembayaranKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Cari");

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Multiply_50px.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        tbTunggakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTunggakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTunggakanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTunggakan);

        txtCariDtTagihan.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtCariDtTagihan.setForeground(new java.awt.Color(0, 102, 255));
        txtCariDtTagihan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtCariDtTagihan.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        txtCariDtTagihan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariDtTagihanKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addGap(612, 612, 612))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addGap(612, 612, 612))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKeluar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCariDtTagihan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCaridtPembayaran, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariDtTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCaridtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 0, 840, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        // TODO add your handling code here:
        String no_rek,no_pel,lunas = "lunas";
        int badmin = 2500;
        
        no_rek = txtNoRek.getText();
        no_pel = txtNoPel.getText();
            
        if (no_rek.equals("") || no_pel.equals("") || tanggal.equals("")) { 
        JOptionPane.showMessageDialog(null, "Lengkapi Data Tagihan!");
        } else {
        String sqlByr = "UPDATE `pembayaran` SET `tanggal_pembayaran` = ?, `b_admin` = ?, `status_pembayaran` = ? WHERE `no_pel` = "+no_pel+"";
        String sqlPlg = "UPDATE `pelanggan` SET `pembayaran_terakhir` = ? WHERE `no_pel` = "+no_pel+"";
        try {
            PreparedStatement statByr = conn.prepareStatement(sqlByr);
            statByr.setString(1, tanggal);
            statByr.setInt(2, badmin);
            statByr.setString(3, lunas);
            statByr.executeUpdate();
            PreparedStatement statPlg = conn.prepareStatement(sqlPlg);
            statPlg.setString(1, tanggal);
            statPlg.executeUpdate();
            int furqonTanya = JOptionPane.showConfirmDialog(null, "Cetak Bukti Pembayaran?", "Cetak Dialog", JOptionPane.YES_NO_OPTION);
            if(furqonTanya==0){
            Connection konek = new koneksi0387().connect();
            InputStream file = getClass().getResourceAsStream("/furqon0387/ctkRek.jrxml");
            JasperDesign jd = JRXmlLoader.load(file);
            HashMap param = new HashMap();
            param.put("norek", txtNoRek.getText());
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, konek);
            JasperViewer jv = new JasperViewer(jp,false);
            
            txtNoRek.setText(null);
            txtNoPel.setText(null);
            txtNama.setText(null);
            cbGol.setSelectedItem(null);
            txtPemakaian.setText(null);
            txtTagihan.setText(null);
            datatabelbyr();
            datatabeltgk();
            
            jv.setTitle("Cektak Bukti Pembayaran");
            jv.setVisible(true);
            }
            
            txtNoRek.setText(null);
            txtNoPel.setText(null);
            txtNama.setText(null);
            cbGol.setSelectedItem(null);
            txtPemakaian.setText(null);
            txtTagihan.setText(null);
            datatabelbyr();
            datatabeltgk();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e + "Data Tagihan Tidak Ditemukan");
        }   catch (JRException ex) {
                Logger.getLogger(dtPembayaranPlg0387.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void btnBersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBersihMouseClicked
        // TODO add your handling code here:
        btnCheckout.setVisible(false);
        txtNoRek.setText(null);
        txtNoPel.setText(null);
        txtNama.setText(null);
        cbGol.setSelectedItem(null);
        txtPemakaian.setText(null);
        txtTagihan.setText(null);
    }//GEN-LAST:event_btnBersihMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
            menuUtmKsr0387 menuUtm = new menuUtmKsr0387();
            menuUtm.show();
            this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtNamaOverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaOverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaOverKeyTyped

    private void txtNoPelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPelKeyPressed

    private void txtNoRekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoRekKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoRekKeyPressed

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        // TODO add your handling code here:
        if(txtNama.getText().length()>45) {
            txtNamaOver.setText("Terlalu Panjang!");
        } else {
            txtNamaOver.setText("");
        }
    }//GEN-LAST:event_txtNamaKeyReleased

    private void txtCariDtTagihanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDtTagihanKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)tbTunggakan.getModel();
        String search = txtCariDtTagihan.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tbTunggakan.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + search));
    }//GEN-LAST:event_txtCariDtTagihanKeyReleased

    private void tbTunggakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTunggakanMouseClicked
        // TODO add your handling code here:
        btnCheckout.setVisible(true);
        
        int bar = tbTunggakan.getSelectedRow();
        TableModel model = tbTunggakan.getModel();

        txtNoRek.setText(model.getValueAt(bar,0).toString());
        txtNoPel.setText(model.getValueAt(bar,1).toString());
        txtNama.setText(model.getValueAt(bar,2).toString());
        cbGol.setSelectedItem(model.getValueAt(bar,3).toString());
        txtPemakaian.setText(model.getValueAt(bar,5).toString());
        txtTagihan.setText(model.getValueAt(bar,7).toString());
    }//GEN-LAST:event_tbTunggakanMouseClicked

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void txtCaridtPembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaridtPembayaranKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)tbPembayaran.getModel();
        String search = txtCaridtPembayaran.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tbPembayaran.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + search));
    }//GEN-LAST:event_txtCaridtPembayaranKeyReleased

    private void tbPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPembayaranMouseClicked
        // TODO add your handling code here:
        btnCheckout.setVisible(false);
        
        int bar = tbPembayaran.getSelectedRow();
        TableModel model = tbPembayaran.getModel();

        txtNoRek.setText(model.getValueAt(bar,0).toString());
        txtNoPel.setText(model.getValueAt(bar,1).toString());
        txtNama.setText(model.getValueAt(bar,2).toString());
        cbGol.setSelectedItem(model.getValueAt(bar,3).toString());
        txtPemakaian.setText(model.getValueAt(bar,5).toString());
        txtTagihan.setText(model.getValueAt(bar,7).toString());
    }//GEN-LAST:event_tbPembayaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dtPembayaranPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dtPembayaranPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dtPembayaranPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dtPembayaranPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dtPembayaranPlg0387().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBersih;
    private javax.swing.JLabel btnCheckout;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JComboBox cbGol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jrJk;
    private javax.swing.JTable tbPembayaran;
    private javax.swing.JTable tbTunggakan;
    private javax.swing.JTextField txtCariDtTagihan;
    private javax.swing.JTextField txtCaridtPembayaran;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel txtNamaOver;
    private javax.swing.JLabel txtNoOver;
    private javax.swing.JTextField txtNoPel;
    private javax.swing.JTextField txtNoRek;
    private javax.swing.JTextField txtPemakaian;
    private javax.swing.JTextField txtTagihan;
    // End of variables declaration//GEN-END:variables

}

