/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furqon0387;

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author furqo
 */
public class dtPgw0387 extends javax.swing.JFrame {
    private Connection conn = new koneksi0387().connect();
    private DefaultTableModel tabmode;
    
    protected void datatabel(){
        Object[] Baris ={"NIP","Nama","Jenis Kelamin","Tempat Lahir","Tanggal Lahir","Alamat","No HP","user","Jabatan"};
        tabmode = new DefaultTableModel(null, Baris);
        jtFurqontable.setModel(tabmode);
        String sql = "SELECT * FROM `pegawai` WHERE `level` = 1 OR `level` = 2 OR `level` = 3";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                Object[] obj = new Object[9];
                obj[0] = hasil.getString("nip");
                obj[1] = hasil.getString("nama");
                obj[2] = hasil.getString("jk");
                obj[3] = hasil.getString("tempat_lahir");
                obj[4] = hasil.getString("tgl_lahir");
                obj[5] = hasil.getString("alamat");
                obj[6] = hasil.getString("no_telp");
                obj[7] = hasil.getString("username");
                obj[8] = hasil.getString("level");
                
                tabmode.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
      }
    }

    /**
     * Creates new form dtPgw0387
     */
    public dtPgw0387() {
        initComponents();
        datatabel();
        cbJab.setSelectedItem(null);
        cbJk.setSelectedItem(null);
        ChTglLahir.setDate(null);
        btnEdit.setVisible(false);
        btnHapus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrJk = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamPeg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTLhr = new javax.swing.JTextField();
        btnEdit = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        btnBersih = new javax.swing.JLabel();
        txtNohp = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNamaOver = new javax.swing.JLabel();
        txtNoHPOver = new javax.swing.JLabel();
        cbJab = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        ChTglLahir = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        cbJk = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnHapus = new javax.swing.JLabel();
        jpanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFurqontable = new javax.swing.JTable();
        txtCariFurqon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        txtNip = new javax.swing.JLabel();
        no_pel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(60, 30));
        setMinimumSize(new java.awt.Dimension(1250, 675));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans Extrabold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PEGAWAI");

        txtNamPeg.setBackground(new java.awt.Color(0, 102, 255));
        txtNamPeg.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNamPeg.setForeground(new java.awt.Color(255, 255, 255));
        txtNamPeg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNamPeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamPegKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamPegKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pegawai");

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jabatan");

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nomor Telepon Pegawai");

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempat Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        txtTLhr.setBackground(new java.awt.Color(0, 102, 255));
        txtTLhr.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtTLhr.setForeground(new java.awt.Color(255, 255, 255));
        txtTLhr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Available_Updates_50px.png"))); // NOI18N
        btnEdit.setToolTipText("update");
        btnEdit.setMinimumSize(new java.awt.Dimension(88, 50));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Add_50px_2.png"))); // NOI18N
        btnTambah.setToolTipText("tambah");
        btnTambah.setMinimumSize(new java.awt.Dimension(88, 50));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        btnBersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Broom_50px.png"))); // NOI18N
        btnBersih.setToolTipText("bersihkan form");
        btnBersih.setMinimumSize(new java.awt.Dimension(88, 50));
        btnBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBersihMouseClicked(evt);
            }
        });

        txtNohp.setBackground(new java.awt.Color(0, 102, 255));
        txtNohp.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNohp.setForeground(new java.awt.Color(255, 255, 255));
        txtNohp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNohpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNohpKeyTyped(evt);
            }
        });

        txtUser.setBackground(new java.awt.Color(0, 102, 255));
        txtUser.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Back_To_32px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        txtNamaOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNamaOver.setForeground(new java.awt.Color(255, 0, 51));
        txtNamaOver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaOverKeyTyped(evt);
            }
        });

        txtNoHPOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoHPOver.setForeground(new java.awt.Color(255, 0, 51));
        txtNoHPOver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoHPOverKeyTyped(evt);
            }
        });

        cbJab.setBackground(new java.awt.Color(0, 102, 255));
        cbJab.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        cbJab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kasir", "Petugas Lapangan", "Costumer Services" }));

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alamat");

        txtAlamat.setBackground(new java.awt.Color(0, 102, 255));
        txtAlamat.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });

        ChTglLahir.setBackground(new java.awt.Color(0, 102, 255));
        ChTglLahir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        jLabel10.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Kelamin");

        cbJk.setBackground(new java.awt.Color(0, 102, 255));
        cbJk.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        cbJk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));

        jLabel11.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");

        txtPass.setBackground(new java.awt.Color(0, 102, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Trash_Can_50px.png"))); // NOI18N
        btnHapus.setToolTipText("update");
        btnHapus.setMinimumSize(new java.awt.Dimension(88, 50));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTLhr, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ChTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNamaOver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNamPeg)
                                        .addComponent(cbJab, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbJk, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNoHPOver, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPass)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaOver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbJk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTLhr, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(ChTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbJab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHPOver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 680);

        jpanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtFurqontable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)));
        jtFurqontable.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jtFurqontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFurqontable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFurqontableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFurqontable);

        txtCariFurqon.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtCariFurqon.setForeground(new java.awt.Color(0, 102, 255));
        txtCariFurqon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtCariFurqon.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        txtCariFurqon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariFurqonKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Cari");

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Multiply_50px.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        txtNip.setForeground(new java.awt.Color(255, 255, 255));
        txtNip.setText("jLabel10");

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addGap(562, 562, 562))
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNip)
                                    .addComponent(no_pel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnKeluar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtCariFurqon))
                        .addContainerGap())))
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addComponent(btnKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(no_pel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(txtCariFurqon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jpanel1);
        jpanel1.setBounds(420, 0, 830, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatKeyTyped

    private void txtAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatKeyReleased

    private void txtNoHPOverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoHPOverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPOverKeyTyped

    private void txtNamaOverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaOverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaOverKeyTyped

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        menuUtmMng0387 menuUtm = new menuUtmMng0387();
        menuUtm.show();
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyReleased

    private void txtNohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNohpKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNohpKeyTyped

    private void txtNohpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNohpKeyReleased
        // TODO add your handling code here:
        String nomorFurqon = txtNohp.getText();
        if(txtNohp.getText().length()>12) {
            txtNoHPOver.setText("Terlalu Panjang!");
        } else {
            txtNoHPOver.setText("");
        }
        if (nomorFurqon.matches("[0-9]*")) {
        } else {
            JOptionPane.showMessageDialog(null, "Nomor Telepon Harus Angka!");
        }
    }//GEN-LAST:event_txtNohpKeyReleased

    private void btnBersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBersihMouseClicked
        // TODO add your handling code here:
        txtNip.setText(null);
        txtNamPeg.setText(null);
        cbJk.setSelectedItem(null);
        txtAlamat.setText(null);
        txtNohp.setText(null);
        txtTLhr.setText(null);
        txtUser.setText(null);
        cbJab.setSelectedItem(null);
        txtNip.requestFocus();
        ChTglLahir.setDate(null);
        txtPass.setText(null);
        btnEdit.setVisible(false);
        btnHapus.setVisible(false);
        btnTambah.setVisible(true);
    }//GEN-LAST:event_btnBersihMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        String nama,jk,tgl,alamat,tLahir,nohp,jabatan,user,pass;

        nama = txtNamPeg.getText();
        jk = String.valueOf(cbJk.getSelectedItem());
        tLahir = txtTLhr.getText();
        Date tl = ChTglLahir.getDate();
        alamat = txtAlamat.getText();
        jabatan = String.valueOf(cbJab.getSelectedItem());
        nohp = txtNohp.getText();
        user = txtUser.getText();
        pass = txtPass.getText();

        if (nama.equals("") || alamat.equals("") || nohp.equals("") || tl.equals("") || tLahir.equals("") || jabatan.equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data yang akan di input!");
        } else {
            String sql = "INSERT INTO `pegawai` (`nama`,`jk`, `tempat_lahir`, `tgl_lahir`, `alamat`, `no_telp`, `username`, `password`, `level`) VALUES (?,?,?,?,?,?,?,MD5(?),?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jk);
                stat.setString(3, tLahir);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tgl = sdf.format(ChTglLahir.getDate());
                stat.setString(4, tgl);
                stat.setString(5, alamat);
                stat.setString(6, nohp);
                stat.setString(7, user);
                stat.setString(8, pass);
                stat.setString(9, jabatan);


                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                txtNip.setText(null);
                txtNamPeg.setText(null);
                cbJk.setSelectedItem(null);
                txtAlamat.setText(null);
                txtNohp.setText(null);
                txtTLhr.setText(null);
                cbJab.setSelectedItem(null);
                txtUser.setText(null);
                txtPass.setText(null);
                ChTglLahir.setDate(null);
                txtNip.requestFocus();
                datatabel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data atau Username sudah ada");
            }
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        String nip,nama,jk,tgl,alamat,tLahir,nohp,jabatan,user,pass;

        nip = txtNip.getText();
        nama = txtNamPeg.getText();
        jk = String.valueOf(cbJk.getSelectedItem());
        tLahir = txtTLhr.getText();
        Date tl = ChTglLahir.getDate();
        alamat = txtAlamat.getText();
        jabatan = String.valueOf(cbJab.getSelectedItem());
        nohp = txtNohp.getText();
        user = txtUser.getText();
        pass = txtPass.getText();

        if (nama.equals("") || alamat.equals("") || nohp.equals("") || tl.equals("") || tLahir.equals("") || jabatan.equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data yang akan di input!");
        } else if (pass.equals("")) {
            String sql = "UPDATE `pegawai` SET `nama` = ?, `jk` = ?, `tempat_lahir` = ?, `tgl_lahir` = ?, `alamat` = ?, `no_telp` = ?, `username` = ?,`level` = ?  WHERE nip = "+nip+"";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jk);
                stat.setString(3, tLahir);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tgl = sdf.format(ChTglLahir.getDate());
                stat.setString(4, tgl);
                stat.setString(5, alamat);
                stat.setString(6, nohp);
                stat.setString(7, user);
                stat.setString(8, jabatan);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Perbarui");
                txtNip.setText(null);
                txtNamPeg.setText(null);
                cbJk.setSelectedItem(null);
                txtAlamat.setText(null);
                txtNohp.setText(null);
                txtTLhr.setText(null);
                cbJab.setSelectedItem(null);
                txtUser.setText(null);
                txtPass.setText(null);
                ChTglLahir.setDate(null);
                btnEdit.setVisible(false);
                btnHapus.setVisible(false);
                btnTambah.setVisible(true);
                txtNip.requestFocus();
                datatabel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,e + "Data sudah ada");
            }
        } else if (!pass.equals("")) {
            String sql = "UPDATE `pegawai` SET `nama` = ?, `jk` = ?, `tempat_lahir` = ?, `tgl_lahir` = ?, `alamat` = ?, `no_telp` = ?, `username` = ?,`password` = MD5(?),`level` = ?  WHERE nip = "+nip+"";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jk);
                stat.setString(3, tLahir);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tgl = sdf.format(ChTglLahir.getDate());
                stat.setString(4, tgl);
                stat.setString(5, alamat);
                stat.setString(6, nohp);
                stat.setString(7, user);
                stat.setString(8, pass);
                stat.setString(9, jabatan);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Perbarui");
                txtNip.setText(null);
                txtNamPeg.setText(null);
                cbJk.setSelectedItem(null);
                txtAlamat.setText(null);
                txtNohp.setText(null);
                txtTLhr.setText(null);
                cbJab.setSelectedItem(null);
                txtUser.setText(null);
                txtPass.setText(null);
                ChTglLahir.setDate(null);
                btnEdit.setVisible(false);
                btnHapus.setVisible(false);
                btnTambah.setVisible(true);
                txtNip.requestFocus();
                datatabel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,e + "Data sudah ada");
            }
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void txtNamPegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamPegKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamPegKeyTyped

    private void txtNamPegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamPegKeyReleased
        // TODO add your handling code here:
        if(txtNamPeg.getText().length()>45) {
            txtNamaOver.setText("Terlalu Panjang!");
        } else {
            txtNamaOver.setText("");
        }
    }//GEN-LAST:event_txtNamPegKeyReleased

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void txtCariFurqonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariFurqonKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jtFurqontable.getModel();
        String search = txtCariFurqon.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jtFurqontable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + search));
    }//GEN-LAST:event_txtCariFurqonKeyReleased

    private void jtFurqontableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFurqontableMouseClicked
        try {
            // TODO add your handling code here:
        int bar = jtFurqontable.getSelectedRow();
        TableModel model = jtFurqontable.getModel();
        
        txtNip.setText(model.getValueAt(bar,0).toString());
        txtNamPeg.setText(model.getValueAt(bar,1).toString());
        cbJk.setSelectedItem(model.getValueAt(bar,2).toString());
        txtTLhr.setText(model.getValueAt(bar, 3).toString());
        Date d = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(bar, 4).toString());
        ChTglLahir.setDate(d);
        txtAlamat.setText(model.getValueAt(bar,5).toString());
        txtNohp.setText(model.getValueAt(bar,6).toString());
        txtUser.setText(model.getValueAt(bar,7).toString());
        cbJab.setSelectedItem(model.getValueAt(bar,8).toString());
            
            btnEdit.setVisible(true);
            btnHapus.setVisible(true);
            btnTambah.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(dtPgw0387.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtFurqontableMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        String nip, nama;

        nip = txtNip.getText();
        nama = txtNamPeg.getText();

        if (nip.equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data yang akan di hapus!");
        } else {
            int furqonTanya = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data "+nama+" dari data pegawai?", "Dialog Hapus", JOptionPane.YES_NO_OPTION);
            if(furqonTanya==0){
            String sql = "DELETE FROM `pegawai` WHERE nip = "+nip+"";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                txtNip.setText(null);
                txtNamPeg.setText(null);
                cbJk.setSelectedItem(null);
                txtAlamat.setText(null);
                txtNohp.setText(null);
                txtTLhr.setText(null);
                cbJab.setSelectedItem(null);
                txtUser.setText(null);
                txtPass.setText(null);
                ChTglLahir.setDate(null);
                btnEdit.setVisible(false);
                btnHapus.setVisible(false);
                btnTambah.setVisible(true);
                datatabel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
      }
    }//GEN-LAST:event_btnHapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dtPgw0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dtPgw0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dtPgw0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dtPgw0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dtPgw0387().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ChTglLahir;
    private javax.swing.JLabel btnBersih;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JComboBox cbJab;
    private javax.swing.JComboBox cbJk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel1;
    private javax.swing.ButtonGroup jrJk;
    private javax.swing.JTable jtFurqontable;
    private javax.swing.JLabel no_pel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCariFurqon;
    private javax.swing.JTextField txtNamPeg;
    private javax.swing.JLabel txtNamaOver;
    private javax.swing.JLabel txtNip;
    private javax.swing.JLabel txtNoHPOver;
    private javax.swing.JTextField txtNohp;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTLhr;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
