/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furqon0387;

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author furqo
 */
public class dtPlg0387 extends javax.swing.JFrame {
    private Connection conn = new koneksi0387().connect();
    private DefaultTableModel tabmode;
    
    protected void datatabel(){
        Object[] Baris ={"No Pelanggan","Nama","Jenis Kelamin","Tempat Lahir","Tanggal Lahir","Alamat","Golongan","No HP","Stand Bulan Lalu","Pembayaran Terakhir"};
        tabmode = new DefaultTableModel(null, Baris);
        jtFurqontable.setModel(tabmode);
        String sql = "SELECT * FROM `pelanggan`";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                Object[] obj = new Object[10];
                obj[0] = hasil.getString("no_pel");
                obj[1] = hasil.getString("nama_pel");
                obj[2] = hasil.getString("jk");
                obj[3] = hasil.getString("tempat_lahir");
                obj[4] = hasil.getString("tgl_lahir");
                obj[5] = hasil.getString("alamat");
                obj[6] = hasil.getString("golongan");
                obj[7] = hasil.getString("no_telp");
                obj[8] = hasil.getString("stand_update");
                obj[9] = hasil.getString("pembayaran_terakhir");
                
                tabmode.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
      }
    }

    /**
     * Creates new form dtPlg0387
     */
    public dtPlg0387() {
        initComponents();
        datatabel();
        cbGol.setSelectedItem(null);
        cbJk.setSelectedItem(null);
        ChTglLahir.setDate(null);
        btnEdit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrJk = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamPel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTLhr = new javax.swing.JTextField();
        btnEdit = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        btnBersih = new javax.swing.JLabel();
        txtNohp = new javax.swing.JTextField();
        txtStandByr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNamaOver = new javax.swing.JLabel();
        txtNoHPOver = new javax.swing.JLabel();
        cbGol = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        ChTglLahir = new com.toedter.calendar.JDateChooser();
        txttrkhrByr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbJk = new javax.swing.JComboBox();
        jpanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFurqontable = new javax.swing.JTable();
        txtCariFurqon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        txtNoPel = new javax.swing.JLabel();
        no_pel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(60, 30));
        setMinimumSize(new java.awt.Dimension(1250, 675));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans Extrabold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PELANGGAN");

        txtNamPel.setBackground(new java.awt.Color(0, 102, 255));
        txtNamPel.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNamPel.setForeground(new java.awt.Color(255, 255, 255));
        txtNamPel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNamPel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamPelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamPelKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pelanggan");

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Golongan");

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nomor Telepon Pelanggan");

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempat Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stand Terakhir & Pembayaran Terakhir  (Di isi oleh sistem)");

        txtTLhr.setBackground(new java.awt.Color(0, 102, 255));
        txtTLhr.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtTLhr.setForeground(new java.awt.Color(255, 255, 255));
        txtTLhr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Available_Updates_50px.png"))); // NOI18N
        btnEdit.setToolTipText("update");
        btnEdit.setMinimumSize(new java.awt.Dimension(88, 50));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Add_50px_2.png"))); // NOI18N
        btnTambah.setToolTipText("tambah");
        btnTambah.setMinimumSize(new java.awt.Dimension(88, 50));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        btnBersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Broom_50px.png"))); // NOI18N
        btnBersih.setToolTipText("bersihkan form");
        btnBersih.setMinimumSize(new java.awt.Dimension(88, 50));
        btnBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBersihMouseClicked(evt);
            }
        });

        txtNohp.setBackground(new java.awt.Color(0, 102, 255));
        txtNohp.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNohp.setForeground(new java.awt.Color(255, 255, 255));
        txtNohp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNohpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNohpKeyTyped(evt);
            }
        });

        txtStandByr.setEditable(false);
        txtStandByr.setBackground(new java.awt.Color(0, 102, 255));
        txtStandByr.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtStandByr.setForeground(new java.awt.Color(255, 255, 255));
        txtStandByr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtStandByr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStandByrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStandByrKeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Back_To_32px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        txtNamaOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNamaOver.setForeground(new java.awt.Color(255, 0, 51));
        txtNamaOver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaOverKeyTyped(evt);
            }
        });

        txtNoHPOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoHPOver.setForeground(new java.awt.Color(255, 0, 51));
        txtNoHPOver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoHPOverKeyTyped(evt);
            }
        });

        cbGol.setBackground(new java.awt.Color(0, 102, 255));
        cbGol.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        cbGol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sosial", "Rumah Tangga", "Industri" }));

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alamat");

        txtAlamat.setBackground(new java.awt.Color(0, 102, 255));
        txtAlamat.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });

        ChTglLahir.setBackground(new java.awt.Color(0, 102, 255));
        ChTglLahir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        txttrkhrByr.setEditable(false);
        txttrkhrByr.setBackground(new java.awt.Color(0, 102, 255));
        txttrkhrByr.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txttrkhrByr.setForeground(new java.awt.Color(255, 255, 255));
        txttrkhrByr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txttrkhrByr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttrkhrByrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttrkhrByrKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Kelamin");

        cbJk.setBackground(new java.awt.Color(0, 102, 255));
        cbJk.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        cbJk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtStandByr, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(94, 94, 94)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttrkhrByr)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNoHPOver, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTLhr, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ChTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNamaOver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNamPel)
                                        .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbJk, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaOver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamPel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbJk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTLhr, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(ChTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHPOver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStandByr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttrkhrByr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 680);

        jpanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtFurqontable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)));
        jtFurqontable.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jtFurqontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFurqontable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFurqontableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFurqontable);

        txtCariFurqon.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtCariFurqon.setForeground(new java.awt.Color(0, 102, 255));
        txtCariFurqon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtCariFurqon.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        txtCariFurqon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariFurqonKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Cari");

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Multiply_50px.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        txtNoPel.setForeground(new java.awt.Color(255, 255, 255));
        txtNoPel.setText("jLabel10");

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addGap(562, 562, 562))
                            .addGroup(jpanel1Layout.createSequentialGroup()
                                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoPel)
                                    .addComponent(no_pel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnKeluar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                        .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtCariFurqon))
                        .addContainerGap())))
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addComponent(btnKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(no_pel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNoPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(txtCariFurqon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jpanel1);
        jpanel1.setBounds(420, 0, 830, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttrkhrByrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttrkhrByrKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrkhrByrKeyTyped

    private void txttrkhrByrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttrkhrByrKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrkhrByrKeyReleased

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatKeyTyped

    private void txtAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatKeyReleased

    private void txtNoHPOverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoHPOverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPOverKeyTyped

    private void txtNamaOverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaOverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaOverKeyTyped

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        menuUtmCs0387 menuUtm = new menuUtmCs0387();
        menuUtm.show();
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtStandByrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStandByrKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStandByrKeyTyped

    private void txtStandByrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStandByrKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStandByrKeyReleased

    private void txtNohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNohpKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNohpKeyTyped

    private void txtNohpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNohpKeyReleased
        // TODO add your handling code here:
        String nomorFurqon = txtNohp.getText();
        if(txtNohp.getText().length()>12) {
            txtNoHPOver.setText("Terlalu Panjang!");
        } else {
            txtNoHPOver.setText("");
        }
        if (nomorFurqon.matches("[0-9]*")) {
        } else {
            JOptionPane.showMessageDialog(null, "Nomor Telepon Harus Angka!");
        }
    }//GEN-LAST:event_txtNohpKeyReleased

    private void btnBersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBersihMouseClicked
        // TODO add your handling code here:
        txtNoPel.setText(null);
        txtNamPel.setText(null);
        cbJk.setSelectedItem(null);
        txtAlamat.setText(null);
        txtNohp.setText(null);
        txtTLhr.setText(null);
        txtStandByr.setText(null);
        cbGol.setSelectedItem(null);
        txtNoPel.requestFocus();
        ChTglLahir.setDate(null);
        txttrkhrByr.setText(null);
        btnEdit.setVisible(false);
        btnTambah.setVisible(true);
    }//GEN-LAST:event_btnBersihMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        String nama,jk,tgl,alamat,tLahir,nohp,golongan;

        long format = System.currentTimeMillis();
        java.sql.Date tglterakhir = new java.sql.Date(format);

        nama = txtNamPel.getText();
        jk = String.valueOf(cbJk.getSelectedItem());
        tLahir = txtTLhr.getText();
        Date tl = ChTglLahir.getDate();
        alamat = txtAlamat.getText();
        golongan = String.valueOf(cbGol.getSelectedItem());
        nohp = txtNohp.getText();
        int stand_akhir = 0;

        if (nama.equals("") || alamat.equals("") || nohp.equals("") || tl.equals("") || tLahir.equals("") || golongan.equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data yang akan di input!");
        } else {
            String sql = "INSERT INTO `pelanggan` (`nama_pel`,`jk`, `tempat_lahir`, `tgl_lahir`, `alamat`, `golongan`, `no_telp`, `stand_update`,`pembayaran_terakhir`,`update_terakhir`) VALUES (?,?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jk);
                stat.setString(3, tLahir);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tgl = sdf.format(ChTglLahir.getDate());
                stat.setString(4, tgl);
                stat.setString(5, alamat);
                stat.setString(6, golongan);
                stat.setString(7, nohp);
                stat.setInt(8, stand_akhir);
                stat.setDate(9, tglterakhir);
                stat.setDate(10, tglterakhir);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                txtNoPel.setText(null);
                txtNamPel.setText(null);
                cbJk.setSelectedItem(null);
                txtAlamat.setText(null);
                txtNohp.setText(null);
                txtTLhr.setText(null);
                cbGol.setSelectedItem(null);
                txtStandByr.setText(null);
                ChTglLahir.setDate(null);
                txttrkhrByr.setText(null);
                txtNoPel.requestFocus();
                datatabel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,e + "Data sudah ada");
            }
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        String no_pel,jk,nama,tgl,alamat,tLahir,nohp,golongan;

        no_pel = txtNoPel.getText();
        jk = String.valueOf(cbJk.getSelectedItem());
        nama = txtNamPel.getText();
        tLahir = txtTLhr.getText();
        Date tl = ChTglLahir.getDate();
        alamat = txtAlamat.getText();
        golongan = String.valueOf(cbGol.getSelectedItem());
        nohp = txtNohp.getText();

        if (nama.equals("") || alamat.equals("") || nohp.equals("") || tl.equals("") || tLahir.equals("") || golongan.equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data yang akan di Edit!");
        } else {
            String sql = "UPDATE `pelanggan` SET nama_pel=?, jk=?, tempat_lahir=?, tgl_lahir=?, alamat=?, golongan=?, no_telp=? WHERE `pelanggan`.`no_pel`='"+no_pel+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jk);
                stat.setString(3, tLahir);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tgl = sdf.format(ChTglLahir.getDate());
                stat.setString(4, tgl);
                stat.setString(5, alamat);
                stat.setString(6, golongan);
                stat.setString(7, nohp);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
                txtNoPel.setText(null);
                cbJk.setSelectedItem(null);
                txtNamPel.setText(null);
                txtAlamat.setText(null);
                txtNohp.setText(null);
                txtTLhr.setText(null);
                cbGol.setSelectedItem(null);
                txtStandByr.setText(null);
                ChTglLahir.setDate(null);
                txttrkhrByr.setText(null);
                txtNoPel.requestFocus();
                datatabel();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Diupdate "+e);
            }
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void txtNamPelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamPelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamPelKeyTyped

    private void txtNamPelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamPelKeyReleased
        // TODO add your handling code here:
        if(txtNamPel.getText().length()>45) {
            txtNamaOver.setText("Terlalu Panjang!");
        } else {
            txtNamaOver.setText("");
        }
    }//GEN-LAST:event_txtNamPelKeyReleased

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void txtCariFurqonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariFurqonKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jtFurqontable.getModel();
        String search = txtCariFurqon.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jtFurqontable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + search));
    }//GEN-LAST:event_txtCariFurqonKeyReleased

    private void jtFurqontableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFurqontableMouseClicked
        try {
            // TODO add your handling code here:
            int bar = jtFurqontable.getSelectedRow();
            TableModel model = jtFurqontable.getModel();
            String a = tabmode.getValueAt(bar, 0).toString();
            String b = tabmode.getValueAt(bar, 1).toString();
            String c = tabmode.getValueAt(bar, 2).toString();
            String tl = tabmode.getValueAt(bar, 3).toString();
            Date d = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(bar, 4).toString());
            String e = tabmode.getValueAt(bar, 5).toString();
            String f = tabmode.getValueAt(bar, 6).toString();
            String g = tabmode.getValueAt(bar, 7).toString();
            String h = tabmode.getValueAt(bar, 8).toString();
            String i = tabmode.getValueAt(bar, 9).toString();
            txtNoPel.setText(a);
            txtNamPel.setText(b);
            cbJk.setSelectedItem(c);
            txtTLhr.setText(tl);
            ChTglLahir.setDate(d);
            txtAlamat.setText(e);
            cbGol.setSelectedItem(f);
            txtNohp.setText(g);
            txtStandByr.setText(h);
            txttrkhrByr.setText(i);
            btnEdit.setVisible(true);
            btnTambah.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(dtPlg0387.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtFurqontableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dtPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dtPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dtPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dtPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dtPlg0387().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ChTglLahir;
    private javax.swing.JLabel btnBersih;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JComboBox cbGol;
    private javax.swing.JComboBox cbJk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel1;
    private javax.swing.ButtonGroup jrJk;
    private javax.swing.JTable jtFurqontable;
    private javax.swing.JLabel no_pel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCariFurqon;
    private javax.swing.JTextField txtNamPel;
    private javax.swing.JLabel txtNamaOver;
    private javax.swing.JLabel txtNoHPOver;
    private javax.swing.JLabel txtNoPel;
    private javax.swing.JTextField txtNohp;
    private javax.swing.JTextField txtStandByr;
    private javax.swing.JTextField txtTLhr;
    private javax.swing.JTextField txttrkhrByr;
    // End of variables declaration//GEN-END:variables
}
