/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furqon0387;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.util.Calendar;
import javax.swing.table.TableModel;

/**
 *
 * @author furqo
 */
public class inpTagihanPlg0387 extends javax.swing.JFrame {
    private Connection conn = new koneksi0387().connect();
    private DefaultTableModel tabmode;
    Calendar cal = Calendar.getInstance();
    int tahun = cal.get(Calendar.YEAR);
    int bulan = cal.get(Calendar.MONTH) + 1;
    int hari = cal.get(Calendar.DAY_OF_MONTH);
    String tanggal = tahun+"-"+bulan+"-"+hari;
    
    protected void datatabelplg(){
        Object[] Baris ={"No Pelanggan","Nama Pelanggan","Golongan","Alamat","Stand Bulan Lalu"};
        tabmode = new DefaultTableModel(null, Baris);
        tbPelanggan.setModel(tabmode);
        String sql = "SELECT * FROM `pelanggan` WHERE MONTH(`update_terakhir`) < "+bulan+"";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                Object[] obj = new Object[5];
                obj[0] = hasil.getString("no_pel");
                obj[1] = hasil.getString("nama_pel");
                obj[2] = hasil.getString("golongan");
                obj[3] = hasil.getString("alamat");
                obj[4] = hasil.getString("stand_update");
                tabmode.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
      }         
    }
    private DefaultTableModel tabelmode;
    
    protected void datatabelbyr(){
        Object[] Baris ={"No Rekening","No Pelanggan","Nama Pelanggan","Golongan","Alamat","Pemakaian","Tanggal Bayar","Tagihan","Status"};
        tabmode = new DefaultTableModel(null, Baris);
        tbPembayaran.setModel(tabmode);
        String sql = "SELECT * FROM `pembayaran` WHERE MONTH(`update_stand`) = "+bulan+" AND `status_pembayaran` = 1;";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                Object[] obj = new Object[9];
                obj[0] = hasil.getString("no_rek");
                obj[1] = hasil.getString("no_pel");
                obj[2] = hasil.getString("nama_pel");
                obj[3] = hasil.getString("golongan");
                obj[4] = hasil.getString("alamat");
                obj[5] = hasil.getString("pemakaian");
                obj[6] = hasil.getString("tanggal_pembayaran");
                obj[7] = hasil.getString("tagihan");
                obj[8] = hasil.getString("status_pembayaran");
                tabmode.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
      }
    }

    /**
     * Creates new form inpTagihanPlg0387
     */
    public inpTagihanPlg0387() {
        initComponents();
        txtStandAkhir.requestFocus();
        btnTambah.setVisible(false);
        cbGol.setSelectedItem(null);
        datatabelplg();
        datatabelbyr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrJk = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNoPel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNpm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        btnBersih = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStandAkhir = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNoOver = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaOver = new javax.swing.JLabel();
        txtNoRek = new javax.swing.JTextField();
        cbGol = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtStandAwal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPembayaran = new javax.swing.JTable();
        txtCariFurqon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPelanggan = new javax.swing.JTable();
        txtCariMhsFurqon = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(60, 30));
        setMinimumSize(new java.awt.Dimension(1250, 675));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans Extrabold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INPUT TAGIHAN");

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nomor Rekening");

        txtNoPel.setEditable(false);
        txtNoPel.setBackground(new java.awt.Color(0, 102, 255));
        txtNoPel.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoPel.setForeground(new java.awt.Color(255, 255, 255));
        txtNoPel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoPel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPelKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Pelanggan");

        txtNpm.setEditable(false);
        txtNpm.setBackground(new java.awt.Color(0, 102, 255));
        txtNpm.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNpm.setForeground(new java.awt.Color(255, 255, 255));
        txtNpm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNpmActionPerformed(evt);
            }
        });
        txtNpm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNpmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNpmKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pelanggan");

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Available_Updates_50px.png"))); // NOI18N
        btnTambah.setMinimumSize(new java.awt.Dimension(88, 50));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        btnBersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Broom_50px.png"))); // NOI18N
        btnBersih.setMinimumSize(new java.awt.Dimension(88, 50));
        btnBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBersihMouseClicked(evt);
            }
        });

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(0, 102, 255));
        txtNama.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Stand Akhir (Isi Form Ini Saja)");

        txtStandAkhir.setBackground(new java.awt.Color(0, 102, 255));
        txtStandAkhir.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtStandAkhir.setForeground(new java.awt.Color(255, 255, 255));
        txtStandAkhir.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        txtAlamat.setEditable(false);
        txtAlamat.setBackground(new java.awt.Color(0, 102, 255));
        txtAlamat.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel12.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alamat");

        txtNoOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoOver.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Back_To_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        txtNamaOver.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNamaOver.setForeground(new java.awt.Color(255, 0, 0));
        txtNamaOver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaOverKeyTyped(evt);
            }
        });

        txtNoRek.setEditable(false);
        txtNoRek.setBackground(new java.awt.Color(0, 102, 255));
        txtNoRek.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtNoRek.setForeground(new java.awt.Color(255, 255, 255));
        txtNoRek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoRek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoRekKeyPressed(evt);
            }
        });

        cbGol.setBackground(new java.awt.Color(0, 102, 255));
        cbGol.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        cbGol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sosial", "Rumah Tangga", "Industri" }));

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Golongan");

        txtStandAwal.setEditable(false);
        txtStandAwal.setBackground(new java.awt.Color(0, 102, 255));
        txtStandAwal.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtStandAwal.setForeground(new java.awt.Color(255, 255, 255));
        txtStandAwal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel15.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Stand Awal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                                .addComponent(txtStandAkhir, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtStandAwal, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtNoOver, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(txtNpm)
                                .addGap(374, 374, 374)
                                .addComponent(txtNamaOver, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNoPel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnBersih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNoRek, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoRek, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(txtNpm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoPel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoOver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaOver, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStandAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStandAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 680);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbPembayaran.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)));
        tbPembayaran.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        tbPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        tbPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPembayaran);

        txtCariFurqon.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtCariFurqon.setForeground(new java.awt.Color(0, 102, 255));
        txtCariFurqon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtCariFurqon.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        txtCariFurqon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariFurqonKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Cari");

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Multiply_50px.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        tbPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPelanggan);

        txtCariMhsFurqon.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        txtCariMhsFurqon.setForeground(new java.awt.Color(0, 102, 255));
        txtCariMhsFurqon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        txtCariMhsFurqon.setSelectedTextColor(new java.awt.Color(0, 102, 255));
        txtCariMhsFurqon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMhsFurqonKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKeluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addGap(612, 612, 612))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addGap(612, 612, 612))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCariFurqon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCariMhsFurqon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariMhsFurqon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariFurqon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 0, 840, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void tbPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPembayaranMouseClicked
        // TODO add your handling code here:
        int bar = tbPelanggan.getSelectedRow();
        TableModel model = tbPelanggan.getModel();
        
        txtNoRek.setText(model.getValueAt(bar,0).toString());
        txtNoPel.setText(model.getValueAt(bar,1).toString());
        txtNama.setText(model.getValueAt(bar,2).toString());
        cbGol.setSelectedItem(model.getValueAt(bar,3).toString());
        txtAlamat.setText(model.getValueAt(bar,4).toString());
        txtStandAwal.setText(model.getValueAt(bar,5).toString());
    }//GEN-LAST:event_tbPembayaranMouseClicked

    private void txtCariFurqonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariFurqonKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)tbPembayaran.getModel();
        String search = txtCariFurqon.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tbPembayaran.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + search));
    }//GEN-LAST:event_txtCariFurqonKeyReleased

    private void txtCariMhsFurqonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMhsFurqonKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)tbPelanggan.getModel();
        String search = txtCariMhsFurqon.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tbPelanggan.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + search));
    }//GEN-LAST:event_txtCariMhsFurqonKeyReleased

    private void tbPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPelangganMouseClicked
        // TODO add your handling code here:
        btnTambah.setVisible(true);
        int bar = tbPelanggan.getSelectedRow();
        TableModel model = tbPelanggan.getModel();
        
        txtNoPel.setText(model.getValueAt(bar,0).toString());
        txtNama.setText(model.getValueAt(bar,1).toString());
        cbGol.setSelectedItem(model.getValueAt(bar,2).toString());
        txtAlamat.setText(model.getValueAt(bar,3).toString());
        txtStandAwal.setText(model.getValueAt(bar,4).toString());

    }//GEN-LAST:event_tbPelangganMouseClicked

    private void txtNoRekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoRekKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoRekKeyPressed

    private void txtNamaOverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaOverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaOverKeyTyped

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        menuUtmPtl0387 menuUtm = new menuUtmPtl0387();
        menuUtm.show();
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        // TODO add your handling code here:
        if(txtNama.getText().length()>45) {
            txtNamaOver.setText("Terlalu Panjang!");
        } else {
            txtNamaOver.setText("");
        }
    }//GEN-LAST:event_txtNamaKeyReleased

    private void btnBersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBersihMouseClicked
        // TODO add your handling code here:
        txtNoRek.setText(null);
        txtNoPel.setText(null);
        txtNama.setText(null);
        cbGol.setSelectedItem(null);
        txtAlamat.setText(null);
        txtStandAkhir.setText(null);
        btnTambah.setVisible(false);
        txtStandAkhir.requestFocus();
    }//GEN-LAST:event_btnBersihMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        String no_pel,nam_pel,golongan,alamat,tunggak = "tunggakan";
        Double tagihan,standawal,standakhir,pemakaian;
        
        long format = System.currentTimeMillis();  
        java.sql.Date tgl = new java.sql.Date(format);  

        no_pel = txtNoPel.getText();
        nam_pel = txtNama.getText();
        alamat = txtAlamat.getText();
        golongan = String.valueOf(cbGol.getSelectedItem());
        
        standawal = Double.parseDouble(txtStandAwal.getText());
        standakhir = Double.parseDouble(txtStandAkhir.getText());
        pemakaian = standakhir - standawal;

        if (golongan == "Sosial") {
            tagihan = pemakaian*2000;
        } else if (golongan == "Rumah Tangga") {
            tagihan = pemakaian*5000;
        } else {
            tagihan = pemakaian*10000;
        }

        if (standakhir.equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data Tagihan!");
        } else {
            String sqlTgh = "INSERT INTO `pembayaran` (`no_pel`, `nama_pel`, `golongan`, `alamat`, `stand_awal`, `stand_akhir`, `update_stand`, `pemakaian`, `tagihan`, `tanggal_pembayaran`, `status_pembayaran`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?);";
            String sqlPlg = "UPDATE `pelanggan` SET `stand_update` = ?, `update_terakhir` = ? WHERE `pelanggan`.`no_pel` = "+no_pel+";";
            try {
                PreparedStatement statTgh = conn.prepareStatement(sqlTgh);
                statTgh.setString(1, no_pel);
                statTgh.setString(2, nam_pel);
                statTgh.setString(3, golongan);
                statTgh.setString(4, alamat);
                statTgh.setDouble(5, standawal);
                statTgh.setDouble(6, standakhir);
                statTgh.setDate(7, tgl);
                statTgh.setDouble(8, pemakaian);
                statTgh.setDouble(9, tagihan);
                statTgh.setString(10, tunggak);
                statTgh.executeUpdate();
                PreparedStatement statPlg = conn.prepareStatement(sqlPlg);
                statPlg.setDouble(1, standakhir);
                statPlg.setDate(2, tgl);
                statPlg.executeUpdate();
                JOptionPane.showMessageDialog(null, "Pembayaran Berhasil");
                txtNoRek.setText(null);
                txtNoPel.setText(null);
                txtNama.setText(null);
                cbGol.setSelectedItem(null);
                txtAlamat.setText(null);
                txtStandAkhir.setText(null);
                txtStandAwal.setText(null);
                btnTambah.setVisible(false);
                datatabelbyr();
                datatabelplg();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e + "Data Pelanggan Tidak Ada atau Belum Ada - Pastikan Nomor Pelanggan Terdaftar");
            }
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void txtNpmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNpmKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNpmKeyTyped

    private void txtNpmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNpmKeyReleased
        // TODO add your handling code here:
        String npmFurqon = txtNpm.getText();
        if(txtNpm.getText().length()>10) {
            txtNoOver.setText("Terlalu Panjang!");
        } else {
            txtNoOver.setText("");
        }
        if (npmFurqon.matches("[0-9]*")) {
        } else {
            JOptionPane.showMessageDialog(null, "Nomor Pokok Mahasiswa Harus Angka!");
        }
    }//GEN-LAST:event_txtNpmKeyReleased

    private void txtNpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNpmActionPerformed

    private void txtNoPelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inpTagihanPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inpTagihanPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inpTagihanPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inpTagihanPlg0387.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inpTagihanPlg0387().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBersih;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JComboBox cbGol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jrJk;
    private javax.swing.JTable tbPelanggan;
    private javax.swing.JTable tbPembayaran;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCariFurqon;
    private javax.swing.JTextField txtCariMhsFurqon;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel txtNamaOver;
    private javax.swing.JLabel txtNoOver;
    private javax.swing.JTextField txtNoPel;
    private javax.swing.JTextField txtNoRek;
    private javax.swing.JTextField txtNpm;
    private javax.swing.JTextField txtStandAkhir;
    private javax.swing.JTextField txtStandAwal;
    // End of variables declaration//GEN-END:variables

}

